"$schema" = "./node_modules/wrangler/config-schema.json"

main = "dist/_worker.js/index.js"
name = "thanhdanhme"
compatibility_date = "2026-02-02"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
